---
version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    container_name: zookeeper
    env_file: zookeper.env


  kafka-broker:
    image: confluentinc/cp-kafka:6.2.0
    container_name: kafka-broker
    ports:
      - "9092:9092"
    depends_on:
        - zookeeper
    env_file: kafka.env

  kafka-setup:
    image: confluentinc/cp-kafka:6.2.0
    container_name: kafka-setup
    depends_on:
      - kafka-broker
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
               cub kafka-ready -b kafka-broker:9092 1 20 && \
               kafka-topics --create --if-not-exists --zookeeper zookeeper:2181 --partitions 1 --replication-factor 1 --topic ${KAFKA_TOPIC}'"
    environment:
      KAFKA_BROKER_ID: ignored
      KAFKA_ZOOKEEPER_CONNECT: ignored

  home-architekt-producer:
    container_name: producer
    depends_on:
      - kafka-broker
      - kafka-setup
    build: ./home-architekt-producer
    image: home-architekt-producer:${HOME_ARCHITEKT_VERSION}
    ports:
      - "8000:8000"
    env_file: home-architekt-common.env

  spark-master:
    image: docker.io/bitnami/spark:3
    container_name: spark-master
    env_file: home-architekt-service/spark-master.env
    ports:
      - '8080:8080'

  spark-worker:
    image: docker.io/bitnami/spark:3
    container_name: spark-worker
    env_file: home-architekt-service/spark-worker.env

