---
version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    container_name: zookeeper
    env_file: .env


  broker:
    image: confluentinc/cp-kafka:6.2.0
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    env_file: .env


  init:
    image: confluentinc/cp-kafka:6.2.0
    container_name: init
    depends_on:
      - broker
    env_file: .env
    command: bash -c "kafka-topics --bootstrap-server broker:9092 --create --topic ${KAFKA_TOPIC}"

  producers-sim:
    container_name: producers-sim
    depends_on:
      - broker
      - init
    build:
      context: .
    ports:
      - "8000:8000"
    env_file: .env
