# Default values for outlier-detector.

image:
  repository: danduta/outlier-detector
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
spark:
  service:
    type: ClusterIP
  worker:
    extraVolumes:
      - name: checkpoint
        emptyDir: { }
    extraVolumeMounts:
      - name: checkpoint
        mountPath: /tmp/cp
  master:
    extraVolumes:
      - name: checkpoint
        emptyDir: { }
    extraVolumeMounts:
      - name: checkpoint
        mountPath: /tmp/cp

kafka:
  rbac:
    create: true
  externalAccess:
    enabled: true
    service:
      type: LoadBalancer
    autoDiscovery:
      enabled: true
  deleteTopicEnable: true
  replicaCount: 2
