apiVersion: v1
kind: Service
metadata:
  name: outlier-detector-external
  labels:
    app: outlier-detector
spec:
  type: LoadBalancer
  ports:
  - port: 4040
    name: spark-ui
  selector:
    app: outlier-detector
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: outlier-detector
spec:
  replicas: 1
  serviceName: outlier-detector-external
  selector:
    matchLabels:
      app: outlier-detector
  template:
    metadata:
      name: outlier-detector
      labels:
        app: outlier-detector
    spec:
      containers:
      - name: spark-driver
        image: danduta/outlier-detector:latest
        env:
        - name: KAFKA_ENDPOINT
          value: http://kafka.default.svc.cluster.local:9092
        - name: SPARK_ENDPOINT
          value: spark://spark-master-svc.default.svc.cluster.local:7077
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: outlier-detector-cp
          mountPath: /tmp/cp
      restartPolicy: Always
      volumes:
        - name: outlier-detector-cp
          emptyDir: {}

