service:
  type: LoadBalancer
worker:
  extraVolumes:
    - name: checkpoint
      emptyDir: { }
  extraVolumeMounts:
    - name: checkpoint
      mountPath: /tmp/cp
master:
  extraVolumes:
    - name: checkpoint
      emptyDir: { }
  extraVolumeMounts:
    - name: checkpoint
      mountPath: /tmp/cp
