service:
  type: LoadBalancer
worker:
  extraVolumes:
    - name: checkpoint
      emptyDir: { }
  extraVolumeMounts:
    - name: checkpoint
      mountPath: /tmp/cp
  extraEnvVars:
    - name: "KAFKA_ENDPOINT"
      value: "http://34.79.246.215:9094"
master:
  extraVolumes:
    - name: checkpoint
      emptyDir: { }
  extraVolumeMounts:
    - name: checkpoint
      mountPath: /tmp/cp
  extraEnvVars:
    - name: "KAFKA_ENDPOINT"
      value: "http://34.79.246.215:9094"

