apiVersion: v1
kind: Service
metadata:
  name: {{ include "outlier-detector.fullname" . }}-external
  labels:
    {{- include "outlier-detector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: spark-ui
      protocol: TCP
      name: spark-ui
  selector:
    {{- include "outlier-detector.selectorLabels" . | nindent 4 }}
